version: '3.4'

services:
  questforge.characterservice:
    image: ${DOCKER_REGISTRY-}questforgecharacterservice
    networks:
          - questforge-network
    build:
      context: .
      dockerfile: QuestForge.CharacterService\Dockerfile

    ports:
    - "5000:5000"

    environment:
        ASPNETCORE_URLS: "https://+:5000"

  database:
    user: root    
    container_name: Database
    networks:
      - questforge-network
    restart: always
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "QuestForge123!@"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - ../volumes/mssql_data:/var/opt/mssql/data

networks:
  questforge-network:
    driver: bridge
